### ISSUE TITLE
Move Discovery deployment to CloudFoundry

### ISSUE THREAD

**Issue by kaitlin** [PSHCDevOps/discovery#401]
By the time we ATO'd, the cloud cutter infrastructure was being deprecated. Should move to Cloud Foundry instance at earliest possible convenience. 

Afterwards, we should debug the swagger UI doc issues with cross domain, and possibly even upgrade the swagger package to swagger 2.0.

**Comment by adrianwebb** [comment]
This has been completed.  Discovery now deploys to the FedRamp'd cloud.gov infrastructure.
