### ISSUE TITLE
Update and improve fixtures

### ISSUE THREAD

**Issue by stvnrlly** [PSHCDevOps/discovery#419]
The fixtures are old, and possibly out of date. I think that this involves a couple of steps:
- [ ] Updating the [CSVs of vendors](https://github.com/18F/discovery/tree/master/vendor/docs)
- [ ] Running the steps in [README.md](https://github.com/18F/discovery/blob/master/README.md) to create new fixtures

Since loading the vendors and then pulling data from SAM and FPDS can take some time, I think it would also be useful to have a fixture of the final data to load into the tool. That might help avoid downtime for the tool while new data is being loaded. A command to run the manual steps and produce that fixture would be awesome.

**Comment by mtorres253** [comment]
Congratulations @dsiddy on winning this micro-purchase auction!

To get started, please create a pull request referencing this issue. Then enter the URL to your pull request on the auction page (in 18F's Micro-purchase platform) and click "start work".

**Comment by adrianwebb** [comment]
This has been completed.  Updated fixtures and fixture generation scripts.
