### ISSUE TITLE
Update the 18F logo

### ISSUE THREAD

**Issue by awfrancisco** [PSHCDevOps/discovery#636]
The logo on the homepage is the old 18F logo. It should be replaced by the current 18F logo available on the [18F brand site](https://brand.18f.gov/logo/).

**Comment by adrianwebb** [comment]
Gotcha, we'll get this in the next release.  Thanks!

**Comment by adrianwebb** [comment]
https://github.com/PSHCDevOps/discovery/pull/639

**Comment by adrianwebb** [comment]
Now on production.
